---
Name: goldfinch-imaginarium
After:
  - 'assetsimage'
---

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\Imaginarium\Extensions\ImageExtension
    - Goldfinch\Imaginarium\Extensions\WebpExtension
   # ! all properties should be in descending order
  imaginarium:
    breakpoints:
      xl: 1210
      lg: 992
      md: 768
      sm: 576
    breakpointsMax:
      xl: 1174
      lg: 960
      md: 720
      sm: 540
    gutters:
      xl: 12
      lg: 12
      md: 12
      sm: 12
    mediaQueries:
      xl:
        - '(min-width: %w) and (min-device-pixel-ratio: 2.0)'
        - '(min-width: %w)'
      lg:
        - '(min-width: %w) and (min-device-pixel-ratio: 2.0)'
        - '(min-width: %w)'
      md:
        - '(min-width: %w) and (min-device-pixel-ratio: 2.0)'
        - '(min-width: %w)'
      sm:
        - '(min-width: %w) and (min-device-pixel-ratio: 2.0)'
        - '(min-width: %w)'
