---
Name: goldfinch-imaginarium
After:
  - 'assetsimage'
---

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\Imaginarium\Extensions\ImageExtension

# SilverStripe\Assets\Storage\DBFile:
#   extensions:
#     - Goldfinch\Imaginarium\Extensions\ImageFormatExtension
